version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: ghostserverd/filebot
    docker:
      - image: cimg/base:current-22.04
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:5.1.x .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:5.1.x
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: 5.1.x
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: 5.1.x
          context: DOCKER_CREDS
  build-on-schedule:
    jobs:
      - build
      - publish-latest:
          requires:
            - build
          context: DOCKER_CREDS
    # The cron format is:
    # min (0-59) hour (0-23) monthday (1-31) month (1-12) weekday (0-6, 0=Sun)
    triggers:
      - schedule:
          cron: "30 7 * * 2"
          filters:
            branches:
              only:
                - 5.1.x
