#!/usr/bin/with-contenv bash

LISTEN_PORT=${FILEBOT_PORT:-7676}
FILEBOT_FORMAT=${FILEBOT_FORMAT:-'{plex}'}
UT_DIR='$v_path'
UT_TITLE='$v_name'
UT_LABEL='$v_label'

exec \
  s6-setuidgid abc /app/shell2http \
    -port=${LISTEN_PORT} \
    -show-errors \
    -include-stderr \
    -form /amc \
    "filebot -script fn:amc --output /media --action duplicate --conflict auto -non-strict -no-xattr --log-file /config/amc.log \
    --def unsorted=y clean=y music=y artwork=y subtitles=en \
    movieFormat=\"${FILEBOT_FORMAT}\" \
    seriesFormat=\"${FILEBOT_FORMAT}\" \
    animeFormat=\"${FILEBOT_FORMAT}\" \
    musicFormat=\"${FILEBOT_FORMAT}\" \
    excludeList="/config/.excludes" \
    ut_dir=\"$UT_DIR\" \
    ut_kind=\"multi\" \
    ut_title=\"$UT_TITLE\" \
    ut_label=\"$UT_LABEL\""
