#!/usr/bin/with-contenv bash

# initialize filebot
filebot -script fn:sysinfo && \

# build symlink for filebot
mkdir -p /data/.filebot && \
ln -s /data/cache/ /data/.filebot/ && \

# chown filebot files
chown -R abc:abc \
        /usr/share/filebot \
        /config \
        /data
