#!/usr/bin/with-contenv bash
cat <<"EOF"
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
         _               _
    __ _| |__   ___  ___| |_
   / _` | '_ \ / _ \/ __| __/
  | (_| | | | | (_) \__ \ |_
   \__, |_| |_|\___/|___/\__|
   |___/      /   _ \
          (¯\| o (@) |/¯)
           \_  .___.  _/
            /   !_!   \
           /_.--._.--._\

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
EOF

# opensubtitles
if [ ! -z $OPEN_SUB_USER ] && [ ! -z $OPEN_SUB_PASS ]
then
    echo "authenticating with opensubtitles"
    printf "%s\n" $OPEN_SUB_USER $OPEN_SUB_PASS | filebot -script fn:configure
fi

# permissions
chown -R abc:abc \
        /config \
        /data

echo "licensing filebot"
filebot --license /config/license.psm
chown -R abc:abc /data
